modLoader = "javafml"
loaderVersion = "[26,)"
license = "CC0-1.0"
issueTrackerURL="https://github.com/MrNavaStar/ProtoWeaver/issues"

[[mods]]
modId = "protoweaver"
version = "0.debug-build"
displayName = "ProtoWeaver"
displayURL="https://github.com/MrNavaStar/ProtoWeaver"
authors="MrNavaStar"
description = "A networking library for creating custom protocols that run on the internal netty server."

displayTest="IGNORE_ALL_VERSION"